TI-2731 - Enable users to log issues with help desk/Jira
IMQS/messaging pull request #3
Opened 2018-06-05 10:45 UTC by stewartm83

Please review

2018-06-05 13:15 UTC, dbferreira requested changes

2018-06-05 13:15 UTC, dbferreira commented on atlassion/atlassion.go
> +package atlassion
I think this should read `atlassian` (also rename folder)

2018-06-05 13:15 UTC, dbferreira commented on httphandler.go
> +	type successJson struct {
I think it's standard practice to define the types at the start of the module file (I could be wrong).

2018-06-06 07:46 UTC, RoanBrand requested changes

2018-06-06 07:46 UTC, RoanBrand commented on httphandler.go
> +		s.Log.Infof("Unable to log issue with the Jira Api: %v", err.Error())
Change log level to warn or error

2018-06-06 07:46 UTC, RoanBrand commented on httphandler.go
> +	resultJson, err := json.Marshal(&result)
Rather:

```
enc := json.NewEncoder(w)
w.Header().Set("Content-Type", "application/json")
err = enc.Encode(&result)
if err != nil {
    ...
}
```

`json.Marshal` allocates memory by creating a byte slice. using the encoder you will achieve the same result but spare resources.

2018-06-06 07:46 UTC, RoanBrand commented on httphandler.go
> +	if contentType == "multipart/form-data" && issueKey != "" {
what if this `if` isn't taken? `statusCode` would be 0 and still used

2018-06-06 08:43 UTC, merged